# Generated by Django 3.1.4 on 2020-12-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_auto_20201223_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='owner/photos', verbose_name='Фото'),
        ),
    ]
