# Generated by Django 3.1.4 on 2020-12-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_animals_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='media/owner/photos', verbose_name='Фото'),
        ),
    ]
