# Generated by Django 3.1.4 on 2020-12-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_auto_20201223_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='owner/photos', verbose_name='Фото'),
        ),
    ]
