# Generated by Django 3.1.4 on 2020-12-24 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_auto_20201223_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.animals')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
